### ISSUE TITLE
finalize preserveHeaderCase change

### ISSUE THREAD

**Issue by natebosch** [dart-lang/http_multi_server#23]
Added without forwarding in #22

Once the SDK change is finalized we can publish. Once an SDK is published with the new argument we can pass it through and bump the min SDK constraint.

**Comment by ZichangG** [comment]
I'll keep track of SDK change and update once it is landed.

**Comment by ZichangG** [comment]
Can we close the issue? This is already published.

**Comment by natebosch** [comment]
I think we're waiting for the min SDK version which allows the argument so that we can start forwarding it. Has and SDK been published with this argument?

**Comment by ZichangG** [comment]
Not yet. I just landed last week. I think it gonna take a while.

One more thing I probably need to do is to tagging. DEPS file now still takes commit hash instead of a valid version.

**Comment by natebosch** [comment]
> One more thing I probably need to do is to tagging. DEPS file now still takes commit hash instead of a valid version.

You can use `2.2.0` as the tag, it is published and forwards compatible with the change.

We'll hold this issue open until we have a minimum SDK we can depend on with the change, and then we'll add the forwarding and close the issue.
